<?php
// data/routes.php

$routeDatabase = [

    'It Park-Colon' => [
        [
            'id' => 'opt1', 'map_color' => '#5cb85c',
            'title' => '17B Modern Jeep',
            'tag'   => 'Direct • 1 ride',
            'desc'  => 'Via Escario & Fuente Osmeña',
            'normal' => ['time'=>'35 mins','fare'=>'₱20','wait'=>'8–12 mins','status'=>'🟢 Clear'],
            'rush'   => ['time'=>'70 mins','fare'=>'₱20','wait'=>'40–50 mins','status'=>'🔴 Heavy'],
            'stops'  => ['IT Park','Escario St','Fuente Osmeña','Jones Ave','Colon'],
            'photo'  => 'images/image1.jpg',
        ],
        [
            'id' => 'opt2', 'map_color' => '#0275d8',
            'title' => 'CIBUS + Jeep',
            'tag'   => 'Transfer at SM • 2 rides',
            'desc'  => 'Bus to SM City, jeep to Colon',
            'normal' => ['time'=>'40 mins','fare'=>'₱33','wait'=>'5–10 mins','status'=>'🟢 Clear'],
            'rush'   => ['time'=>'55 mins','fare'=>'₱33','wait'=>'20–25 mins','status'=>'🟡 Moderate'],
            'stops'  => ['IT Park','Ayala','SM City ⇄','Jones Ave','Colon'],
            'photo'  => 'images/image2.jpg',
        ],
        [
            'id' => 'opt3', 'map_color' => '#f0ad4e',
            'title' => 'Angkas + BRT',
            'tag'   => 'Fastest • 2 rides',
            'desc'  => 'Motorbike to Fuente, BRT to Colon',
            'normal' => ['time'=>'22 mins','fare'=>'₱85', 'wait'=>'2 mins','status'=>'🟢 Fastest'],
            'rush'   => ['time'=>'30 mins','fare'=>'₱110','wait'=>'5 mins','status'=>'🟢 Bypasses Traffic'],
            'stops'  => ['IT Park','Fuente Osmeña ⇄','Carbon BRT','Colon'],
            'photo'  => 'images/image3.jpg',
        ],
        [
            'id' => 'opt4', 'map_color' => '#d9534f',
            'title' => '17C Jeep',
            'tag'   => 'Cheapest • 1 ride',
            'desc'  => 'Via F. Ramos & P. del Rosario',
            'normal' => ['time'=>'40 mins','fare'=>'₱14','wait'=>'12–18 mins','status'=>'🟢 Clear'],
            'rush'   => ['time'=>'85 mins','fare'=>'₱14','wait'=>'50+ mins',  'status'=>'🔴 Very Slow'],
            'stops'  => ['IT Park','F. Ramos St','P. del Rosario','Jones Ave','Colon'],
            'photo'  => 'images/image4.jpg',
        ],
    ],

    'Mandaue-Colon' => [
        [
            'id' => 'opt1', 'map_color' => '#5cb85c',
            'title' => '01K Direct Jeep',
            'tag'   => 'Cheapest • 1 ride',
            'desc'  => 'Via A.S. Fortuna & Jones Ave',
            'normal' => ['time'=>'45 mins','fare'=>'₱18','wait'=>'8–12 mins','status'=>'🟡 Moderate'],
            'rush'   => ['time'=>'95 mins','fare'=>'₱18','wait'=>'1 hr+',    'status'=>'🔴 Very Slow'],
            'stops'  => ['Mandaue','A.S. Fortuna','SM City','Jones Ave','Colon'],
            'photo'  => 'images/image5.jpg',
        ],
        [
            'id' => 'opt2', 'map_color' => '#0275d8',
            'title' => 'Jeep + BRT',
            'tag'   => 'Balanced • 2 rides',
            'desc'  => 'Jeep to SM, BRT beats the traffic',
            'normal' => ['time'=>'38 mins','fare'=>'₱29','wait'=>'5–8 mins','status'=>'🟢 Good'],
            'rush'   => ['time'=>'52 mins','fare'=>'₱29','wait'=>'15 mins', 'status'=>'🟢 Bypasses Gridlock'],
            'stops'  => ['Mandaue','A.S. Fortuna','SM City ⇄','Carbon BRT','Colon'],
            'photo'  => 'images/image6.jpg',
        ],
        [
            'id' => 'opt3', 'map_color' => '#f0ad4e',
            'title' => 'MyBus A/C',
            'tag'   => 'Comfortable • 1 ride + walk',
            'desc'  => 'Fixed-schedule bus, 8-min walk at end',
            'normal' => ['time'=>'32 mins','fare'=>'₱30','wait'=>'15–20 mins','status'=>'🟢 A/C'],
            'rush'   => ['time'=>'48 mins','fare'=>'₱30','wait'=>'20 mins',   'status'=>'🟡 Standing Room'],
            'stops'  => ['Mandaue','SM North Wing','Reclamation Rd','Compañia Marítima','Colon (walk)'],
            'photo'  => 'images/sample.jpg',
        ],
    ],

    'Mandaue-It Park' => [
        [
            'id' => 'opt1', 'map_color' => '#5cb85c',
            'title' => '22I Jeep via Banilad',
            'tag'   => 'Budget • 1 ride',
            'desc'  => 'Through Banilad & Talamban',
            'normal' => ['time'=>'28 mins','fare'=>'₱15','wait'=>'8–12 mins', 'status'=>'🟢 Clear'],
            'rush'   => ['time'=>'65 mins','fare'=>'₱15','wait'=>'25–35 mins','status'=>'🔴 Bottleneck'],
            'stops'  => ['Mandaue','Ouano Ave','Banilad','Talamban Rd','IT Park'],
            'photo'  => 'images/image8.jpg',
        ],
        [
            'id' => 'opt2', 'map_color' => '#f0ad4e',
            'title' => 'Angkas / Habal',
            'tag'   => 'Fastest • 1 ride',
            'desc'  => 'Door-to-door motorbike, back roads',
            'normal' => ['time'=>'15 mins','fare'=>'₱70', 'wait'=>'2–3 mins', 'status'=>'🟢 Fast'],
            'rush'   => ['time'=>'25 mins','fare'=>'₱160','wait'=>'5–10 mins','status'=>'🔴 Surge Pricing'],
            'stops'  => ['Mandaue','IT Park'],
            'photo'  => 'images/image9.jpg',
        ],
        [
            'id' => 'opt3', 'map_color' => '#0275d8',
            'title' => '20B + 17B Jeep',
            'tag'   => 'Reliable • 2 rides',
            'desc'  => 'Via Ayala Center transfer',
            'normal' => ['time'=>'42 mins','fare'=>'₱29','wait'=>'8 mins',    'status'=>'🟡 Moderate'],
            'rush'   => ['time'=>'68 mins','fare'=>'₱29','wait'=>'25–30 mins','status'=>'🟡 Long Queue'],
            'stops'  => ['Mandaue','Basak','Ayala Center ⇄','IT Park'],
            'photo'  => 'images/image10.jpg',
        ],
    ],
];
